play = [
    { run = 'vlc "$@"', desc = "VLC", orphan = true }
]

[manager]
linemode = "size" # default = "none"
ratio = [2, 3, 5] # default = [1, 4, 3]

[preview]
max_width       = 3024 # default = 600
max_height      = 1964 # default = 900

[open]
rules = [
  { mime = "video/*", use = [ "play", "reveal" ] },
]

